### ISSUE TITLE
Simulate node functionality.

### ISSUE THREAD

**Issue by DylanPiercey** [bevry/domain-browser#10]
This is probably out of scope for this module but I think more feature parity with node could be achieved using https://github.com/angular/zone.js/.

**Comment by balupton** [comment]
The caution here is whether or not providing the illusion that domains work (work ≈ have feature parity) in the browser (a false positive) is better for preventing errors in the apps than only implementing the fundamentals and having the developer aware this is a non-perfect workaround.

Arguably, the fundamentals will be different for different people it seems - as such perhaps we should implement as much as we can, but log warnings the more and more egregious the lack of actual support the browser APIs have compared to the node APIs.

**Comment by DylanPiercey** [comment]
Understandable. Its too bad that the functionality for domains, zones and continuations is so hard to implement in javascript.

I think as close as possible is a good goal for this module. I have been playing around with zone.js today and it seems like it would be a good candidate to mimic some of the functionality in the browser but it is also ~7kb gzip so not the lightest dependency.
